Only add to ignored columns if necessary
globalize/globalize pull request #806
Opened 2023-01-11 22:14 UTC by stiak

At least in rails 5.2 adding anything to ignored columns makes rails switch to explicit columns in model queries.  I'd prefer to keep the .* to keep the queries easy to read in our monitoring.

I'd love a pointer to an appropriate place to add tests for these changes.

2023-05-22 22:51 UTC, stiak commented
Still waiting for a review here

2024-11-28 22:03 UTC, stiak commented
@rocket-turtle I saw mention of this PR over on https://github.com/globalize/globalize/pull/825

I've rebased against latest main, are there any other changes you'd like to see?

2024-11-29 03:23 UTC, parndt commented on lib/globalize/active_record/act_macro.rb
> +            unless (column_names & translated_attribute_name_strings).empty?
```suggestion
            if (column_names & translated_attribute_name_strings).any?
```

I find this easier to read

2024-11-29 03:24 UTC, parndt commented
Sorry @stiak I didn't see this earlier! I've approved CI to run

2024-12-02 22:22 UTC, stiak commented
> Sorry @stiak I didn't see this earlier! I've approved CI to run

Thanks @parndt, I agree positive logic checks are easier to read 👍 I've added your suggestion.

2024-12-03 08:33 UTC, rocket-turtle requested changes

2024-12-03 22:14 UTC, stiak commented on lib/globalize/active_record/act_macro.rb
> +              self.ignored_columns += translated_attribute_names.map(&:to_s)
Ok, I've added that in

2024-12-05 02:39 UTC, parndt approved these changes

2024-12-05 02:41 UTC, parndt commented
Thank you! Can you please add this to the CHANGELOG.md file (you can put it under a new title "unreleased" for now)?

2024-12-05 07:50 UTC, rocket-turtle approved these changes

2024-12-06 02:28 UTC, parndt approved these changes

2024-12-06 02:37 UTC, merged

2024-12-06 02:37 UTC, parndt commented
Thank you!